# Fast baseline configuration for CMFD
# Target: Good balance of speed and accuracy

backbone: dinov2_vits14
freeze_backbone: true

# Correlation parameters
patch: 12
stride: 4
top_k: 5

# Geometric verification
ransac_model: similarity
inlier_thresh_px: 1.5
inlier_growth: 5
corr_threshold: 0.7

# Test-time augmentation
tta: flip

# Post-processing
post:
  thr: 0.5
  min_area: 24
  morph:
    close: 3
    open: 0

# Training
training:
  batch_size: 8
  epochs: 50
  lr: 0.0001
  seed: 42
