# Configuration optimized for detecting tiny cloned regions
# Uses smaller patches and more matches

backbone: dinov2_vits14
freeze_backbone: true

# Correlation parameters - optimized for small regions
patch: 8
stride: 4
top_k: 7

# Geometric verification
ransac_model: similarity
inlier_thresh_px: 1.5
inlier_growth: 5
corr_threshold: 0.7

# Test-time augmentation
tta: flip

# Post-processing - lower min_area for tiny regions
post:
  thr: 0.5
  min_area: 12
  morph:
    close: 3
    open: 0

# Training
training:
  batch_size: 8
  epochs: 50
  lr: 0.0001
  seed: 42
